### ISSUE TITLE
Demostrar exemplos de variáveis/operações matemáticas e controle de fluxo em python

### ISSUE THREAD

**Issue by luiscarlosjunior** [luiscarlosjunior/aulas-graduacao#28]
**Exemplos simples com breves comentários**

- [x]  Declaração e exibição de variáveis (todos os tipos primitivos); 

- [x] Exemplo usando os operadores matemáticos;
- [x] Exemplo de controle fluxo (if-else if- else);

**Obs: Pode ser feito usando o COLAB**

**Comment by luiscarlosjunior** [comment]
@rcj91 vou assinar para a mim essa **issues**. Já tenho alguns exemplos que podem ser aproveitados.

**Comment by rcj91** [comment]
import os
#Declaração e exibição de variáveis (todos os tipos primitivos);

# Declarando variável idade e sobrenome
idade = 43
sobrenome = "Silva" 

# Exibindo as variáveis usando o print

texto = "Eu sou Ricardo {} e minha idade é {}"
print(texto.format(sobrenome,idade)) 

# Exemplo usando os operadores matemáticos;

# Equação: V = R*I, descobrir valor V

# Declarando valores

R = 10000
I = 3 
V = R*I

# Printando o valor de V

print('Valor de V é:', V)


# Exemplo de controle fluxo (if-else if- else - switch);

#Verificar se arquivo existe

if os.path.exists("novoarquivo22222.txt"):
    print("Arquivo existe")
else:
    print("Arquivo não existe")
    f = open("novoarquivo22222.txt", "x")
    print("E agora...Arquivo criado")

**Comment by luiscarlosjunior** [comment]
@rcj91 ficou legal, acredito que dá para usar na página Wiki. Contudo eu preciso de exemplos usando o COLAB para que os alunos tenham o conteúdo. Segue um exemplo de conteúdo esperado [Exemplos de aula sobre medidas de dispersão](https://github.com/luiscarlosjunior/aulas-graduacao/blob/master/Data%20science/Analise%20de%20dados/An%C3%A1lise%20com%20python/Aula_08_Medidas_de_dispers%C3%A3o.ipynb)

**Comment by luiscarlosjunior** [comment]
## Exemplos simples sobre a estrutura da linguagem de programação **Python**
```
import os
#Declaração e exibição de variáveis (todos os tipos primitivos);

# Declarando variável idade e sobrenome
idade = 43
sobrenome = "Silva"
 
# Exibindo as variáveis usando o print
texto = "Eu sou Ricardo {} e minha idade é {}"
print(texto.format(sobrenome,idade))
 
# Exemplo usando os operadores matemáticos;
# Equação: V = R*I, descobrir valor V
# Declarando valores
R = 10000
I = 3
V = R*I
 
# Printando o valor de V
print('Valor de V é:', V)
 
# Exemplo de controle fluxo (if-else if- else - switch);

#Verificar se arquivo existe
if os.path.exists("novoarquivo22222.txt"):
     print("Arquivo existe")
     f = open("novoarquivo.txt", "x")
     print("Arquivo aberto")
else:
     print("Arquivo não existe")
```


>obs: Revisão sobre o conteúdo postado. Quando inserir trechos de códigos é preferivel utilizar os comandos ``` código aqui ```` para melhor representar.

**Comment by luiscarlosjunior** [comment]
@rcj91 Devolvi essa issue para você

**Comment by rcj91** [comment]
@luiscarlosjunior como eu faço para colocar um arquivo colab aqui?

**Comment by rcj91** [comment]
e para revisar essa issue?

**Comment by luiscarlosjunior** [comment]
> @luiscarlosjunior como eu faço para colocar um arquivo colab aqui?

Adicione o arquivo no seu fork e me envie um pull request

**Comment by luiscarlosjunior** [comment]
> @luiscarlosjunior como eu faço para colocar um arquivo colab aqui?

**Comment by luiscarlosjunior** [comment]
> e para revisar essa issue?

Você será notificado

**Comment by Andrelirao** [comment]
@luiscarlosjunior submeti pr #67, favor revisar

**Comment by luiscarlosjunior** [comment]
Peguei de volta para fazer.

**Comment by luiscarlosjunior** [comment]
A issue foi feita, porém é preciso abrir uma nova issue de refatoração.

**Comment by luiscarlosjunior** [comment]
Foi retirado alguns arquivo e mesclados em somente um

**Comment by luiscarlosjunior** [comment]
Esta issue está completa e será fechada. Mais detalhes pode ser visto no commit #126
